# Workflow 名稱
name: My workflow

# 觸發時機
on:
  workflow_dispatch: {}

# 執行的動作(Job)
jobs:
  build:  # Job名稱，也可以用name來重新定義👇
    name: Test-Job          # 定義Job名稱
    runs-on: ubuntu-latest  # 在哪個平台執行
    steps:  # Job的動作
      - name: Say hello     # 這個動作的名稱
      # uses:   # 用到的Github Action
      # with:   # Action 用到的參數
      #   parameter:
      #     .
      #     .
      #     .
        run: echo Hello     # 執行的動作